@props(['selected'])

<option value="AF" {{in_array('AF', $selected) ? 'selected' : ''}}>Afghanistan</option>
<option value="AL" {{in_array('AL', $selected) ? 'selected' : ''}}>Albania</option>
<option value="DZ" {{in_array('DZ', $selected) ? 'selected' : ''}}>Algeria</option>
<option value="AS" {{in_array('AS', $selected) ? 'selected' : ''}}>American Samoa</option>
<option value="AD" {{in_array('AD', $selected) ? 'selected' : ''}}>Andorra</option>
<option value="AO" {{in_array('AO', $selected) ? 'selected' : ''}}>Angola</option>
<option value="AI" {{in_array('AI', $selected) ? 'selected' : ''}}>Anguilla</option>
<option value="AQ" {{in_array('AQ', $selected) ? 'selected' : ''}}>Antarctica</option>
<option value="AG" {{in_array('AG', $selected) ? 'selected' : ''}}>Antigua and Barbuda</option>
<option value="AR" {{in_array('AR', $selected) ? 'selected' : ''}}>Argentina</option>
<option value="AM" {{in_array('AM', $selected) ? 'selected' : ''}}>Armenia</option>
<option value="AW" {{in_array('AW', $selected) ? 'selected' : ''}}>Aruba</option>
<option value="AU" {{in_array('AU', $selected) ? 'selected' : ''}}>Australia</option>
<option value="AT" {{in_array('AT', $selected) ? 'selected' : ''}}>Austria</option>
<option value="AZ" {{in_array('AZ', $selected) ? 'selected' : ''}}>Azerbaijan</option>
<option value="BS" {{in_array('BS', $selected) ? 'selected' : ''}}>Bahamas</option>
<option value="BH" {{in_array('BH', $selected) ? 'selected' : ''}}>Bahrain</option>
<option value="BD" {{in_array('BD', $selected) ? 'selected' : ''}}>Bangladesh</option>
<option value="BB" {{in_array('BB', $selected) ? 'selected' : ''}}>Barbados</option>
<option value="BY" {{in_array('BY', $selected) ? 'selected' : ''}}>Belarus</option>
<option value="BE" {{in_array('BE', $selected) ? 'selected' : ''}}>Belgium</option>
<option value="BZ" {{in_array('BZ', $selected) ? 'selected' : ''}}>Belize</option>
<option value="BJ" {{in_array('BJ', $selected) ? 'selected' : ''}}>Benin</option>
<option value="BM" {{in_array('BM', $selected) ? 'selected' : ''}}>Bermuda</option>
<option value="BT" {{in_array('BT', $selected) ? 'selected' : ''}}>Bhutan</option>
<option value="BO" {{in_array('BO', $selected) ? 'selected' : ''}}>Bolivia, Plurinational State of</option>
<option value="BQ" {{in_array('BQ', $selected) ? 'selected' : ''}}>Bonaire, Sint Eustatius and Saba</option>
<option value="BA" {{in_array('BA', $selected) ? 'selected' : ''}}>Bosnia and Herzegovina</option>
<option value="BW" {{in_array('BW', $selected) ? 'selected' : ''}}>Botswana</option>
<option value="BV" {{in_array('BV', $selected) ? 'selected' : ''}}>Bouvet Island</option>
<option value="BR" {{in_array('BR', $selected) ? 'selected' : ''}}>Brazil</option>
<option value="IO" {{in_array('IO', $selected) ? 'selected' : ''}}>British Indian Ocean Territory</option>
<option value="BN" {{in_array('BN', $selected) ? 'selected' : ''}}>Brunei Darussalam</option>
<option value="BG" {{in_array('BG', $selected) ? 'selected' : ''}}>Bulgaria</option>
<option value="BF" {{in_array('BF', $selected) ? 'selected' : ''}}>Burkina Faso</option>
<option value="BI" {{in_array('BI', $selected) ? 'selected' : ''}}>Burundi</option>
<option value="KH" {{in_array('KH', $selected) ? 'selected' : ''}}>Cambodia</option>
<option value="CM" {{in_array('CM', $selected) ? 'selected' : ''}}>Cameroon</option>
<option value="CA" {{in_array('CA', $selected) ? 'selected' : ''}}>Canada</option>
<option value="CV" {{in_array('CV', $selected) ? 'selected' : ''}}>Cape Verde</option>
<option value="KY" {{in_array('KY', $selected) ? 'selected' : ''}}>Cayman Islands</option>
<option value="CF" {{in_array('CF', $selected) ? 'selected' : ''}}>Central African Republic</option>
<option value="TD" {{in_array('TD', $selected) ? 'selected' : ''}}>Chad</option>
<option value="CL" {{in_array('CL', $selected) ? 'selected' : ''}}>Chile</option>
<option value="CN" {{in_array('CN', $selected) ? 'selected' : ''}}>China</option>
<option value="CX" {{in_array('CX', $selected) ? 'selected' : ''}}>Christmas Island</option>
<option value="CC" {{in_array('CC', $selected) ? 'selected' : ''}}>Cocos (Keeling) Islands</option>
<option value="CO" {{in_array('CO', $selected) ? 'selected' : ''}}>Colombia</option>
<option value="KM" {{in_array('KM', $selected) ? 'selected' : ''}}>Comoros</option>
<option value="CG" {{in_array('CG', $selected) ? 'selected' : ''}}>Congo</option>
<option value="CD" {{in_array('CD', $selected) ? 'selected' : ''}}>Congo, the Democratic Republic of the</option>
<option value="CK" {{in_array('CK', $selected) ? 'selected' : ''}}>Cook Islands</option>
<option value="CR" {{in_array('CR', $selected) ? 'selected' : ''}}>Costa Rica</option>
<option value="CI" {{in_array('CI', $selected) ? 'selected' : ''}}>Côte d'Ivoire</option>
<option value="HR" {{in_array('HR', $selected) ? 'selected' : ''}}>Croatia</option>
<option value="CU" {{in_array('CU', $selected) ? 'selected' : ''}}>Cuba</option>
<option value="CW" {{in_array('CW', $selected) ? 'selected' : ''}}>Curaçao</option>
<option value="CY" {{in_array('CY', $selected) ? 'selected' : ''}}>Cyprus</option>
<option value="CZ" {{in_array('CZ', $selected) ? 'selected' : ''}}>Czech Republic</option>
<option value="DK" {{in_array('DK', $selected) ? 'selected' : ''}}>Denmark</option>
<option value="DJ" {{in_array('DJ', $selected) ? 'selected' : ''}}>Djibouti</option>
<option value="DM" {{in_array('DM', $selected) ? 'selected' : ''}}>Dominica</option>
<option value="DO" {{in_array('DO', $selected) ? 'selected' : ''}}>Dominican Republic</option>
<option value="EC" {{in_array('EC', $selected) ? 'selected' : ''}}>Ecuador</option>
<option value="EG" {{in_array('EG', $selected) ? 'selected' : ''}}>Egypt</option>
<option value="SV" {{in_array('SV', $selected) ? 'selected' : ''}}>El Salvador</option>
<option value="GQ" {{in_array('GQ', $selected) ? 'selected' : ''}}>Equatorial Guinea</option>
<option value="ER" {{in_array('ER', $selected) ? 'selected' : ''}}>Eritrea</option>
<option value="EE" {{in_array('EE', $selected) ? 'selected' : ''}}>Estonia</option>
<option value="ET" {{in_array('ET', $selected) ? 'selected' : ''}}>Ethiopia</option>
<option value="FK" {{in_array('FK', $selected) ? 'selected' : ''}}>Falkland Islands (Malvinas)</option>
<option value="FO" {{in_array('FO', $selected) ? 'selected' : ''}}>Faroe Islands</option>
<option value="FJ" {{in_array('FJ', $selected) ? 'selected' : ''}}>Fiji</option>
<option value="FI" {{in_array('FI', $selected) ? 'selected' : ''}}>Finland</option>
<option value="FR" {{in_array('FR', $selected) ? 'selected' : ''}}>France</option>
<option value="GF" {{in_array('GF', $selected) ? 'selected' : ''}}>French Guiana</option>
<option value="PF" {{in_array('PF', $selected) ? 'selected' : ''}}>French Polynesia</option>
<option value="TF" {{in_array('TF', $selected) ? 'selected' : ''}}>French Southern Territories</option>
<option value="GA" {{in_array('GA', $selected) ? 'selected' : ''}}>Gabon</option>
<option value="GM" {{in_array('GM', $selected) ? 'selected' : ''}}>Gambia</option>
<option value="GE" {{in_array('GE', $selected) ? 'selected' : ''}}>Georgia</option>
<option value="DE" {{in_array('DE', $selected) ? 'selected' : ''}}>Germany</option>
<option value="GH" {{in_array('GH', $selected) ? 'selected' : ''}}>Ghana</option>
<option value="GI" {{in_array('GI', $selected) ? 'selected' : ''}}>Gibraltar</option>
<option value="GR" {{in_array('GR', $selected) ? 'selected' : ''}}>Greece</option>
<option value="GL" {{in_array('GL', $selected) ? 'selected' : ''}}>Greenland</option>
<option value="GD" {{in_array('GD', $selected) ? 'selected' : ''}}>Grenada</option>
<option value="GP" {{in_array('GP', $selected) ? 'selected' : ''}}>Guadeloupe</option>
<option value="GU" {{in_array('GU', $selected) ? 'selected' : ''}}>Guam</option>
<option value="GT" {{in_array('GT', $selected) ? 'selected' : ''}}>Guatemala</option>
<option value="GG" {{in_array('GG', $selected) ? 'selected' : ''}}>Guernsey</option>
<option value="GN" {{in_array('GN', $selected) ? 'selected' : ''}}>Guinea</option>
<option value="GW" {{in_array('GW', $selected) ? 'selected' : ''}}>Guinea-Bissau</option>
<option value="GY" {{in_array('GY', $selected) ? 'selected' : ''}}>Guyana</option>
<option value="HT" {{in_array('HT', $selected) ? 'selected' : ''}}>Haiti</option>
<option value="HM" {{in_array('HM', $selected) ? 'selected' : ''}}>Heard Island and McDonald Islands</option>
<option value="VA" {{in_array('VA', $selected) ? 'selected' : ''}}>Holy See (Vatican City State)</option>
<option value="HN" {{in_array('HN', $selected) ? 'selected' : ''}}>Honduras</option>
<option value="HK" {{in_array('HK', $selected) ? 'selected' : ''}}>Hong Kong</option>
<option value="HU" {{in_array('HU', $selected) ? 'selected' : ''}}>Hungary</option>
<option value="IS" {{in_array('IS', $selected) ? 'selected' : ''}}>Iceland</option>
<option value="IN" {{in_array('IN', $selected) ? 'selected' : ''}}>India</option>
<option value="ID" {{in_array('ID', $selected) ? 'selected' : ''}}>Indonesia</option>
<option value="IR" {{in_array('IR', $selected) ? 'selected' : ''}}>Iran, Islamic Republic of</option>
<option value="IQ" {{in_array('IQ', $selected) ? 'selected' : ''}}>Iraq</option>
<option value="IE" {{in_array('IE', $selected) ? 'selected' : ''}}>Ireland</option>
<option value="IM" {{in_array('IM', $selected) ? 'selected' : ''}}>Isle of Man</option>
<option value="IL" {{in_array('IL', $selected) ? 'selected' : ''}}>Israel</option>
<option value="IT" {{in_array('IT', $selected) ? 'selected' : ''}}>Italy</option>
<option value="JM" {{in_array('JM', $selected) ? 'selected' : ''}}>Jamaica</option>
<option value="JP" {{in_array('JP', $selected) ? 'selected' : ''}}>Japan</option>
<option value="JE" {{in_array('JE', $selected) ? 'selected' : ''}}>Jersey</option>
<option value="JO" {{in_array('JO', $selected) ? 'selected' : ''}}>Jordan</option>
<option value="KZ" {{in_array('KZ', $selected) ? 'selected' : ''}}>Kazakhstan</option>
<option value="KE" {{in_array('KE', $selected) ? 'selected' : ''}}>Kenya</option>
<option value="KI" {{in_array('KI', $selected) ? 'selected' : ''}}>Kiribati</option>
<option value="KP" {{in_array('KP', $selected) ? 'selected' : ''}}>Korea, Democratic People's Republic of</option>
<option value="KR" {{in_array('KR', $selected) ? 'selected' : ''}}>Korea, Republic of</option>
<option value="KW" {{in_array('KW', $selected) ? 'selected' : ''}}>Kuwait</option>
<option value="KG" {{in_array('KG', $selected) ? 'selected' : ''}}>Kyrgyzstan</option>
<option value="LA" {{in_array('LA', $selected) ? 'selected' : ''}}>Lao People's Democratic Republic</option>
<option value="LV" {{in_array('LV', $selected) ? 'selected' : ''}}>Latvia</option>
<option value="LB" {{in_array('LB', $selected) ? 'selected' : ''}}>Lebanon</option>
<option value="LS" {{in_array('LS', $selected) ? 'selected' : ''}}>Lesotho</option>
<option value="LR" {{in_array('LR', $selected) ? 'selected' : ''}}>Liberia</option>
<option value="LY" {{in_array('LY', $selected) ? 'selected' : ''}}>Libya</option>
<option value="LI" {{in_array('LI', $selected) ? 'selected' : ''}}>Liechtenstein</option>
<option value="LT" {{in_array('LT', $selected) ? 'selected' : ''}}>Lithuania</option>
<option value="LU" {{in_array('LU', $selected) ? 'selected' : ''}}>Luxembourg</option>
<option value="MO" {{in_array('MO', $selected) ? 'selected' : ''}}>Macao</option>
<option value="MK" {{in_array('MK', $selected) ? 'selected' : ''}}>Macedonia, the former Yugoslav Republic of</option>
<option value="MG" {{in_array('MG', $selected) ? 'selected' : ''}}>Madagascar</option>
<option value="MW" {{in_array('MW', $selected) ? 'selected' : ''}}>Malawi</option>
<option value="MY" {{in_array('MY', $selected) ? 'selected' : ''}}>Malaysia</option>
<option value="MV" {{in_array('MV', $selected) ? 'selected' : ''}}>Maldives</option>
<option value="ML" {{in_array('ML', $selected) ? 'selected' : ''}}>Mali</option>
<option value="MT" {{in_array('MT', $selected) ? 'selected' : ''}}>Malta</option>
<option value="MH" {{in_array('MH', $selected) ? 'selected' : ''}}>Marshall Islands</option>
<option value="MQ" {{in_array('MQ', $selected) ? 'selected' : ''}}>Martinique</option>
<option value="MR" {{in_array('MR', $selected) ? 'selected' : ''}}>Mauritania</option>
<option value="MU" {{in_array('MU', $selected) ? 'selected' : ''}}>Mauritius</option>
<option value="YT" {{in_array('YT', $selected) ? 'selected' : ''}}>Mayotte</option>
<option value="MX" {{in_array('MX', $selected) ? 'selected' : ''}}>Mexico</option>
<option value="FM" {{in_array('FM', $selected) ? 'selected' : ''}}>Micronesia, Federated States of</option>
<option value="MD" {{in_array('MD', $selected) ? 'selected' : ''}}>Moldova, Republic of</option>
<option value="MC" {{in_array('MC', $selected) ? 'selected' : ''}}>Monaco</option>
<option value="MN" {{in_array('MN', $selected) ? 'selected' : ''}}>Mongolia</option>
<option value="ME" {{in_array('ME', $selected) ? 'selected' : ''}}>Montenegro</option>
<option value="MS" {{in_array('MS', $selected) ? 'selected' : ''}}>Montserrat</option>
<option value="MA" {{in_array('MA', $selected) ? 'selected' : ''}}>Morocco</option>
<option value="MZ" {{in_array('MZ', $selected) ? 'selected' : ''}}>Mozambique</option>
<option value="MM" {{in_array('MM', $selected) ? 'selected' : ''}}>Myanmar</option>
<option value="NA" {{in_array('NA', $selected) ? 'selected' : ''}}>Namibia</option>
<option value="NR" {{in_array('NR', $selected) ? 'selected' : ''}}>Nauru</option>
<option value="NP" {{in_array('NP', $selected) ? 'selected' : ''}}>Nepal</option>
<option value="NL" {{in_array('NL', $selected) ? 'selected' : ''}}>Netherlands</option>
<option value="NC" {{in_array('NC', $selected) ? 'selected' : ''}}>New Caledonia</option>
<option value="NZ" {{in_array('NZ', $selected) ? 'selected' : ''}}>New Zealand</option>
<option value="NI" {{in_array('NI', $selected) ? 'selected' : ''}}>Nicaragua</option>
<option value="NE" {{in_array('NE', $selected) ? 'selected' : ''}}>Niger</option>
<option value="NG" {{in_array('NG', $selected) ? 'selected' : ''}}>Nigeria</option>
<option value="NU" {{in_array('NU', $selected) ? 'selected' : ''}}>Niue</option>
<option value="NF" {{in_array('NF', $selected) ? 'selected' : ''}}>Norfolk Island</option>
<option value="MP" {{in_array('MP', $selected) ? 'selected' : ''}}>Northern Mariana Islands</option>
<option value="NO" {{in_array('NO', $selected) ? 'selected' : ''}}>Norway</option>
<option value="OM" {{in_array('OM', $selected) ? 'selected' : ''}}>Oman</option>
<option value="PK" {{in_array('PK', $selected) ? 'selected' : ''}}>Pakistan</option>
<option value="PW" {{in_array('PW', $selected) ? 'selected' : ''}}>Palau</option>
<option value="PS" {{in_array('PS', $selected) ? 'selected' : ''}}>Palestinian Territory, Occupied</option>
<option value="PA" {{in_array('PA', $selected) ? 'selected' : ''}}>Panama</option>
<option value="PG" {{in_array('PG', $selected) ? 'selected' : ''}}>Papua New Guinea</option>
<option value="PY" {{in_array('PY', $selected) ? 'selected' : ''}}>Paraguay</option>
<option value="PE" {{in_array('PE', $selected) ? 'selected' : ''}}>Peru</option>
<option value="PH" {{in_array('PH', $selected) ? 'selected' : ''}}>Philippines</option>
<option value="PN" {{in_array('PN', $selected) ? 'selected' : ''}}>Pitcairn</option>
<option value="PL" {{in_array('PL', $selected) ? 'selected' : ''}}>Poland</option>
<option value="PT" {{in_array('PT', $selected) ? 'selected' : ''}}>Portugal</option>
<option value="PR" {{in_array('PR', $selected) ? 'selected' : ''}}>Puerto Rico</option>
<option value="QA" {{in_array('QA', $selected) ? 'selected' : ''}}>Qatar</option>
<option value="RE" {{in_array('RE', $selected) ? 'selected' : ''}}>Réunion</option>
<option value="RO" {{in_array('RO', $selected) ? 'selected' : ''}}>Romania</option>
<option value="RU" {{in_array('RU', $selected) ? 'selected' : ''}}>Russian Federation</option>
<option value="RW" {{in_array('RW', $selected) ? 'selected' : ''}}>Rwanda</option>
<option value="BL" {{in_array('BL', $selected) ? 'selected' : ''}}>Saint Barthélemy</option>
<option value="SH" {{in_array('SH', $selected) ? 'selected' : ''}}>Saint Helena, Ascension and Tristan da Cunha</option>
<option value="KN" {{in_array('KN', $selected) ? 'selected' : ''}}>Saint Kitts and Nevis</option>
<option value="LC" {{in_array('LC', $selected) ? 'selected' : ''}}>Saint Lucia</option>
<option value="MF" {{in_array('MF', $selected) ? 'selected' : ''}}>Saint Martin (French part)</option>
<option value="PM" {{in_array('PM', $selected) ? 'selected' : ''}}>Saint Pierre and Miquelon</option>
<option value="VC" {{in_array('VC', $selected) ? 'selected' : ''}}>Saint Vincent and the Grenadines</option>
<option value="WS" {{in_array('WS', $selected) ? 'selected' : ''}}>Samoa</option>
<option value="SM" {{in_array('SM', $selected) ? 'selected' : ''}}>San Marino</option>
<option value="ST" {{in_array('ST', $selected) ? 'selected' : ''}}>Sao Tome and Principe</option>
<option value="SA" {{in_array('SA', $selected) ? 'selected' : ''}}>Saudi Arabia</option>
<option value="SN" {{in_array('SN', $selected) ? 'selected' : ''}}>Senegal</option>
<option value="RS" {{in_array('RS', $selected) ? 'selected' : ''}}>Serbia</option>
<option value="SC" {{in_array('SC', $selected) ? 'selected' : ''}}>Seychelles</option>
<option value="SL" {{in_array('SL', $selected) ? 'selected' : ''}}>Sierra Leone</option>
<option value="SG" {{in_array('SG', $selected) ? 'selected' : ''}}>Singapore</option>
<option value="SX" {{in_array('SX', $selected) ? 'selected' : ''}}>Sint Maarten (Dutch part)</option>
<option value="SK" {{in_array('SK', $selected) ? 'selected' : ''}}>Slovakia</option>
<option value="SI" {{in_array('SI', $selected) ? 'selected' : ''}}>Slovenia</option>
<option value="SB" {{in_array('SB', $selected) ? 'selected' : ''}}>Solomon Islands</option>
<option value="SO" {{in_array('SO', $selected) ? 'selected' : ''}}>Somalia</option>
<option value="ZA" {{in_array('ZA', $selected) ? 'selected' : ''}}>South Africa</option>
<option value="GS" {{in_array('GS', $selected) ? 'selected' : ''}}>South Georgia and the South Sandwich Islands</option>
<option value="SS" {{in_array('SS', $selected) ? 'selected' : ''}}>South Sudan</option>
<option value="ES" {{in_array('ES', $selected) ? 'selected' : ''}}>Spain</option>
<option value="LK" {{in_array('LK', $selected) ? 'selected' : ''}}>Sri Lanka</option>
<option value="SD" {{in_array('SD', $selected) ? 'selected' : ''}}>Sudan</option>
<option value="SR" {{in_array('SR', $selected) ? 'selected' : ''}}>Suriname</option>
<option value="SJ" {{in_array('SJ', $selected) ? 'selected' : ''}}>Svalbard and Jan Mayen</option>
<option value="SZ" {{in_array('SZ', $selected) ? 'selected' : ''}}>Swaziland</option>
<option value="SE" {{in_array('SE', $selected) ? 'selected' : ''}}>Sweden</option>
<option value="CH" {{in_array('CH', $selected) ? 'selected' : ''}}>Switzerland</option>
<option value="SY" {{in_array('SY', $selected) ? 'selected' : ''}}>Syrian Arab Republic</option>
<option value="TW" {{in_array('TW', $selected) ? 'selected' : ''}}>Taiwan, Province of China</option>
<option value="TJ" {{in_array('TJ', $selected) ? 'selected' : ''}}>Tajikistan</option>
<option value="TZ" {{in_array('TZ', $selected) ? 'selected' : ''}}>Tanzania, United Republic of</option>
<option value="TH" {{in_array('TH', $selected) ? 'selected' : ''}}>Thailand</option>
<option value="TL" {{in_array('TL', $selected) ? 'selected' : ''}}>Timor-Leste</option>
<option value="TG" {{in_array('TG', $selected) ? 'selected' : ''}}>Togo</option>
<option value="TK" {{in_array('TK', $selected) ? 'selected' : ''}}>Tokelau</option>
<option value="TO" {{in_array('TO', $selected) ? 'selected' : ''}}>Tonga</option>
<option value="TT" {{in_array('TT', $selected) ? 'selected' : ''}}>Trinidad and Tobago</option>
<option value="TN" {{in_array('TN', $selected) ? 'selected' : ''}}>Tunisia</option>
<option value="TR" {{in_array('TR', $selected) ? 'selected' : ''}}>Turkey</option>
<option value="TM" {{in_array('TM', $selected) ? 'selected' : ''}}>Turkmenistan</option>
<option value="TC" {{in_array('TC', $selected) ? 'selected' : ''}}>Turks and Caicos Islands</option>
<option value="TV" {{in_array('TV', $selected) ? 'selected' : ''}}>Tuvalu</option>
<option value="UG" {{in_array('UG', $selected) ? 'selected' : ''}}>Uganda</option>
<option value="UA" {{in_array('UA', $selected) ? 'selected' : ''}}>Ukraine</option>
<option value="AE" {{in_array('AE', $selected) ? 'selected' : ''}}>United Arab Emirates</option>
<option value="GB" {{in_array('GB', $selected) ? 'selected' : ''}}>United Kingdom</option>
<option value="US" {{in_array('US', $selected) ? 'selected' : ''}}>United States</option>
<option value="UM" {{in_array('UM', $selected) ? 'selected' : ''}}>United States Minor Outlying Islands</option>
<option value="UY" {{in_array('UY', $selected) ? 'selected' : ''}}>Uruguay</option>
<option value="UZ" {{in_array('UZ', $selected) ? 'selected' : ''}}>Uzbekistan</option>
<option value="VU" {{in_array('VU', $selected) ? 'selected' : ''}}>Vanuatu</option>
<option value="VE" {{in_array('VE', $selected) ? 'selected' : ''}}>Venezuela, Bolivarian Republic of</option>
<option value="VN" {{in_array('VN', $selected) ? 'selected' : ''}}>Viet Nam</option>
<option value="VG" {{in_array('VG', $selected) ? 'selected' : ''}}>Virgin Islands, British</option>
<option value="VI" {{in_array('VI', $selected) ? 'selected' : ''}}>Virgin Islands, U.S.</option>
<option value="WF" {{in_array('WF', $selected) ? 'selected' : ''}}>Wallis and Futuna</option>
<option value="EH" {{in_array('EH', $selected) ? 'selected' : ''}}>Western Sahara</option>
<option value="YE" {{in_array('YE', $selected) ? 'selected' : ''}}>Yemen</option>
<option value="ZM" {{in_array('ZM', $selected) ? 'selected' : ''}}>Zambia</option>
<option value="ZW" {{in_array('ZW', $selected) ? 'selected' : ''}}>Zimbabwe</option>
